name: Deploy app

on:
  push:
    branches:
      - feat/workflow

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: Install
        run: yarn install
      - name: Build
        run: | 
            yarn predeploy
            yarn deploy
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
